version: '3.6'

services:
  frontend:
    image: "bxc/ui:latest"
    volumes:
      - ../config/frontend/env.js:/home/node/public/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:www.bitcoinmarket.pro"
      traefik.port: 3000

  tower:
    image: "rubykube/tower:0.1.17"
    volumes:
      - ../config/frontend/tower.js:/home/app/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/tower;Host:www.bitcoinmarket.pro"
      traefik.port: 8080

